Add Image feature extraction on Hub as a task
huggingface/huggingface.js pull request #402
Opened 2023-12-07 14:50 UTC by merveenoyan

This PR adds image feature extraction to Hub.
Icon looks like below 👇 

<img width="141" alt="Screenshot 2023-12-07 at 15 49 53" src="https://github.com/huggingface/huggingface.js/assets/53175384/44fc48eb-2efc-4585-81d1-741e17d07f7e">

2023-12-07 16:04 UTC, mishig25 commented on packages/widgets/src/lib/components/Icons/IconImageFeatureExtraction.svelte
> +>
```suggestion
<script lang="ts">
	export let classNames = "";
</script>

<svg
	class={classNames}
	xmlns="http://www.w3.org/2000/svg"
	xmlns:xlink="http://www.w3.org/1999/xlink"
	aria-hidden="true"
	fill="currentColor"
	focusable="false"
	role="img"
	width="1em"
	height="1em"
	preserveAspectRatio="xMidYMid meet"
	viewBox="0 0 24 24"
>
	<path
		fill="currentColor"
		d="M5 21q-.825 0-1.412-.587T3 19V5q0-.825.588-1.412T5 3h5v2H5v14h14v-5.35l2 2V19q0 .825-.587 1.413T19 21H5Zm1-4l3-4l2.25 3l3-4L18 17H6Zm15.55-3.6l-3.1-3.1q-.525.35-1.125.525T16.05 11q-1.85 0-3.15-1.312T11.6 6.5q0-1.875 1.313-3.187T16.1 2q1.875 0 3.188 1.313T20.6 6.5q0 .675-.2 1.3t-.5 1.15L22.95 12l-1.4 1.4ZM16.1 9q1.05 0 1.775-.725T18.6 6.5q0-1.05-.725-1.775T16.1 4q-1.05 0-1.775.725T13.6 6.5q0 1.05.725 1.775T16.1 9Z"
	/>
</svg>
```

2023-12-07 16:34 UTC, gary149 approved these changes
ok

2023-12-07 21:06 UTC, osanseviero requested changes
This would add a filter/tag that leads to 0 models on the Hub (see https://huggingface.co/models?other=image-feature-extraction&sort=trending). We should first:
* add the tag to the corresponding `transformers` and `timm` repos. Which models would have this tag?
* explore adding the `pipeline` to `transformers`

From a quick look, most models in https://huggingface.co/models?pipeline_tag=feature-extraction&other=vision are candidates to be `image-feature-extraction`. These models are usually automatically tagged, so step 3 in https://www.notion.so/huggingface2/How-do-pipelines-get-determined-on-the-Hub-2fdc2f3ae1a44690b43e28adbe326d11 needs to be done. This also needs to align with the `transformers` team first to see if there's a need for this pipeline/task  cc @LysandreJik @amyeroberts 

There is a very related discussion on https://github.com/huggingface/transformers/issues/20830#issuecomment-1370626529 about this, we should check if `feature-extraction` works for these

2023-12-09 04:13 UTC, merveenoyan commented
@osanseviero  I made a script to run over timm models so I will be autotagging them. There's a lot of backbones on Hub, they're not explored well among other modalities, this is discussed in the issue linked to this PR.

2023-12-09 11:49 UTC, osanseviero commented
>  can do the same for transformers feature-extraction models that are for vision

Please carefully review the resources/Notion linked above. **We should not open PRs for the vision-tagged `transformers` models.** The `pipeline_tag` in `transformers` models is automatically detected, so actually we need to add `ImageFeatureExtractionPipeline` there and update the mapping, which will automatically update the tags for `transformers` repos

2023-12-15 07:02 UTC, merveenoyan commented
@osanseviero 

>  so actually we need to add ImageFeatureExtractionPipeline there and update the mapping, which will automatically update the tags for transformers repos

whom should I confirm with to do so?

2024-02-19 15:49 UTC, osanseviero approved these changes
Thanks!

2024-02-19 15:53 UTC, merged