add publish to GPR support
huggingface/huggingface.js pull request #49
Opened 2023-03-05 08:15 UTC by o-az

This adds support for publishing to GitHub Package Registry (https://github.com/huggingface/huggingface.js/issues/47).

I can merge the two `'*-publish.yml` workflows into one once `changesets` support is added.

2023-03-05 13:53 UTC, coyotte508 requested changes
I had several try/errors on this branch: https://github.com/huggingface/huggingface.js/tree/test-github-publish, so I hope my suggestions are correct.

Basically we should publish both to npm and github packages at once, so that the publishing to github happens after the version was bumped up (otherwise `publish-gpr` and `version_and_release` would run in parallel). 

And no need to specify `working-directory: packages/hub` on the `run` commands, it's already a global setting ealier in the file.

2023-03-05 13:53 UTC, coyotte508 commented on .github/workflows/hub-publish.yml
> +          pnpm publish --access public --registry https://npm.pkg.github.com --no-git-checks
```suggestion
      # hack - reuse actions/setup-node@v3 just to set a new registry 
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://npm.pkg.github.com"
      - run: pnpm publish .
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

2023-03-05 13:53 UTC, coyotte508 commented on .github/workflows/inference-publish.yml
> +          pnpm publish --access public --registry https://npm.pkg.github.com --no-git-checks
```suggestion
      # hack - reuse actions/setup-node@v3 just to set a new registry 
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://npm.pkg.github.com"
      - run: pnpm publish .
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

2023-03-06 18:02 UTC, o-az reviewed
accepted @coyotte508 change requests.

2023-03-06 19:01 UTC, coyotte508 approved these changes

2023-03-06 19:01 UTC, merged

2023-03-06 19:02 UTC, coyotte508 commented
Thanks!