[gguf] get optional `paramCount`
huggingface/huggingface.js pull request #637
Opened 2024-04-25 11:41 UTC by mishig25

2024-04-25 12:22 UTC, mishig25 commented on packages/gguf/src/gguf.ts
> +					const shardParamCount = shardTesnorInfos
handled in 6be0dc120973a5942847cd0ee90bae1da468b01b

2024-04-26 14:12 UTC, ngxson commented
I additionally reviewed this PR. It's LGTM overall.

One small suggestion is that maybe we should abstract/generalize the support for shared gguf (while using the correct metadata) in the future. If you're OK with this idea, I'll have a look on it.

2024-04-26 15:32 UTC, julien-c requested changes

2024-04-26 15:32 UTC, julien-c commented on packages/gguf/src/gguf.ts
> +		calculateParamCount?: boolean;
why not the same parameter name as for safetensors (`computeParametersCount`)?

2024-04-26 15:32 UTC, julien-c commented on packages/gguf/src/types.ts
> +	paramCount?: number;
why not the same prop name as for safetensors (`parameterCount`)? Besides i don't think this should be in this type (which is strictly what is in GGUF), but just in the function return type

2024-04-26 15:32 UTC, julien-c commented on packages/gguf/src/gguf.ts
> +			.reduce((acc, val) => acc + val, 0);
i agree with this part, but shouldn't we return a `Record<Dtype, number>` like in safetensors? (no strong opinion, I'm ok with only returning a number, that's fine)

2024-04-26 15:32 UTC, julien-c commented on packages/gguf/src/gguf.ts
> +		if (ggufShardFileInfo) {
```suggestion
		if (ggufShardFileInfo && params?.fetchAllShards) {
```

IMO this behavior (fetching other shards magically) is quite unintuitive, so I would at least add a special flag for it.

Or maybe better API-wise to split this into another method

2024-04-29 11:11 UTC, julien-c approved these changes

2024-04-29 11:14 UTC, merged